_BASE_: "../../Base-YOLOv7.yaml"
MODEL:
  PIXEL_MEAN: [0.485, 0.456, 0.406] # same value as PP-YOLOv2, RGB order
  PIXEL_STD: [0.229, 0.224, 0.225]

  WEIGHTS: ""
  MASK_ON: False
  META_ARCHITECTURE: "YOLOTr"
  BACKBONE:
    NAME: "build_convnext_backbone"
    WEIGHTS: "weights/efficientformer_l1_1000d.pth"
    OUT_FEATURES: ['norm2', 'norm4', 'norm6']
    TYPE: "l1"

  YOLO:
    CLASSES: 80
    IN_FEATURES: ['norm2', 'norm4', 'norm6'] 
    CONF_THRESHOLD: 0.001
    NMS_THRESHOLD: 0.65
    IGNORE_THRESHOLD: 0.7
    WIDTH_MUL: 1.
    DEPTH_MUL: 1.
    LOSS_TYPE: "v7"
    LOSS:
      LAMBDA_IOU: 1.5

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)

INPUT:
  # FORMAT: "RGB" # using BGR default
  MIN_SIZE_TRAIN: (416, 512, 608, 768)
  MAX_SIZE_TRAIN: 800 # force max size train to 800?
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 800
  # open all augmentations
  JITTER_CROP:
    ENABLED: False
  RESIZE:
    ENABLED: False
    # SHAPE: (540, 960)
  DISTORTION:
    ENABLED: True
  COLOR_JITTER:
    BRIGHTNESS: True
    SATURATION: True
  # MOSAIC:
  #   ENABLED: True
  #   NUM_IMAGES: 4
  #   DEBUG_VIS: True
  #   # MOSAIC_WIDTH: 960
  #   # MOSAIC_HEIGHT: 540
  MOSAIC_AND_MIXUP:
    ENABLED: True
    # ENABLED: False
    DEBUG_VIS: False
    ENABLE_MIXUP: False
    DISABLE_AT_ITER: 120000

SOLVER:
  AMP:
    ENABLED: true
  IMS_PER_BATCH: 16
  BASE_LR: 0.00012
  STEPS: (369600,)
  MAX_ITER: 554400
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    # CLIP_TYPE: "norm"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0

TEST:
  EVAL_PERIOD: 10000
  # EVAL_PERIOD: 0
OUTPUT_DIR: "output/coco_yolotr_efficientformer"
VIS_PERIOD: 5000

DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 3
