_BASE_: "../../Base-YOLOv7.yaml"
MODEL:
  PIXEL_MEAN: [0.485, 0.456, 0.406] # same value as PP-YOLOv2, RGB order
  PIXEL_STD: [0.229, 0.224, 0.225]

  WEIGHTS: ""
  MASK_ON: False
  META_ARCHITECTURE: "YOLOTr"
  BACKBONE:
    NAME: "build_convnext_backbone"

  CONVNEXT:
    WEIGHTS: "weights/convnext_tiny_22k_1k_384.pth"
    DEPTH_WISE: False
    OUT_FEATURES: ['f1', 'f2', 'f3']

  YOLO:
    CLASSES: 80
    # IN_FEATURES: ["dark3", "dark4", "dark5"]
    IN_FEATURES: ['f1', 'f2', 'f3'] 
    CONF_THRESHOLD: 0.001
    NMS_THRESHOLD: 0.65
    IGNORE_THRESHOLD: 0.7
    # WIDTH_MUL: 0.50
    # DEPTH_MUL: 0.33
    WIDTH_MUL: 1.
    DEPTH_MUL: 1.
    LOSS_TYPE: "v7"
    LOSS:
      LAMBDA_IOU: 1.5
    NORMALIZE_INPUT: False

DATASETS:
  TRAIN: ("coco_2017_train",)
  # TEST: ("coco_2014_val_mini",)
  TEST: ("coco_2017_val",)

INPUT:
  # FORMAT: "RGB" # using BGR default
  MIN_SIZE_TRAIN: (576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1080 # force max size train to 800?
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1080
  # open all augmentations
  JITTER_CROP:
    ENABLED: False
  RESIZE:
    ENABLED: False
    # SHAPE: (540, 960)
  DISTORTION:
    ENABLED: True
  COLOR_JITTER:
    BRIGHTNESS: True
    SATURATION: True
  MOSAIC_AND_MIXUP:
    ENABLED: True
    DEBUG_VIS: False
    # DEBUG_VIS: False
    # ENABLE_MIXUP: True
    ENABLE_MIXUP: False
    DISABLE_AT_ITER: 80000 # disable mosaic at iter, also will enable l1 loss then
    MOSAIC_WIDTH_RANGE: [600, 800]
    MOSAIC_HEIGHT_RANGE: [600, 800]
  INPUT_SIZE: [960, 960]

SOLVER:
  AMP:
    ENABLED: true
  IMS_PER_BATCH: 16
  BASE_LR: 0.0002
  STEPS: (40000, 60000, 70000)
  MAX_ITER: 554400
  WARMUP_FACTOR: 1.0
  # WARMUP_ITERS: 1200
  WARMUP_ITERS: 100
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  LR_MULTIPLIER_OVERWRITE:
    [{ "backbone": 0.5 }, { "reference_points": 0.1, "sampling_offsets": 0.1 }]
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    # CLIP_TYPE: "norm"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0

TEST:
  EVAL_PERIOD: 10000
  # EVAL_PERIOD: 0
OUTPUT_DIR: "output/coco_yolotr_convnext_aug"
VIS_PERIOD: 5000

DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 3
